# Generated by Django 5.2.8 on 2025-11-24 19:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Customer's last name", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254, unique=True)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('address', models.TextField(help_text="Customer's mailing address")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the destination', max_length=200)),
                ('country', models.CharField(help_text='Country where destination is located', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the destination')),
                ('image_url', models.URLField(blank=True, help_text='URL to destination image', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the travel package', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField(help_text='Package start date')),
                ('end_date', models.DateField(help_text='Package end date')),
                ('duration_days', models.IntegerField(help_text='Duration of the trip in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('itinerary', models.TextField(help_text='Detailed day-by-day itinerary')),
                ('available_spots', models.IntegerField(help_text='Number of available spots for booking', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='Destination for this travel package', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='project.destination')),
            ],
            options={
                'ordering': ['start_date', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when booking was made')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('number_of_people', models.IntegerField(help_text='Number of people in the booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='project.customer')),
                ('travel_package', models.ForeignKey(help_text='Travel package being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='project.travelpackage')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
